# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8.0
      - image: circleci/openjdk:8-jdk-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Detault JRE
          command: sudo apt-get install default-jre

      - run:
          name: Install Chromium
          command: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list && sudo apt-get update  && sudo apt-get install google-chrome-stable

      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar && sudo cp selenium-server-standalone-3.5.3.jar /bin/selenium.jar && sudo cp ./selenium /bin/selenium && sudo chmod +x /bin/selenium

      - run:
          name: Download Chrome Driver
          command: wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip && unzip ./chromedriver_linux64.zip -d ~/ && rm ./chromedriver_linux64.zip && sudo mv -f ~/chromedriver /usr/local/bin/chromedriver && sudo chown root:root /usr/local/bin/chromedriver && sudo chmod 0755 /usr/local/bin/chromedriver

      - run:
          name: install mocha
          command: sudo npm install -g mocha

      - run: npm -v && node -v

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test


